# This file was @generated by cargo2nix 0.12.0.
# It is not intended to be manually edited.

args@{ release ? true
, rootFeatures ? [
    "rust-test/default"
  ]
, rustPackages
, buildRustPackages
, hostPlatform
, hostPlatformCpu ? null
, hostPlatformFeatures ? [ ]
, target ? null
, codegenOpts ? null
, profileOpts ? null
, cargoUnstableFlags ? null
, rustcLinkFlags ? null
, rustcBuildFlags ? null
, mkRustCrate
, rustLib
, lib
, workspaceSrc
, ignoreLockHash
, cargoConfig ? { }
,
}:
let
  nixifiedLockHash = "ae8143e535fa63099a70b7be6c591a7c43cb93574a80b2d1ed2e8692a7b1e522";
  workspaceSrc = if args.workspaceSrc == null then ./. else args.workspaceSrc;
  currentLockHash = builtins.hashFile "sha256" (workspaceSrc + /Cargo.lock);
  lockHashIgnored =
    if ignoreLockHash
    then builtins.trace "Ignoring lock hash" ignoreLockHash
    else ignoreLockHash;
in
if !lockHashIgnored && (nixifiedLockHash != currentLockHash) then
  throw ("Cargo.nix ${nixifiedLockHash} is out of sync with Cargo.lock ${currentLockHash}")
else
  let
    inherit (rustLib) fetchCratesIo fetchCrateLocal fetchCrateGit fetchCrateAlternativeRegistry expandFeatures decideProfile genDrvsByProfile;
    cargoConfig' = if cargoConfig != { } then cargoConfig else
    if builtins.pathExists ./.cargo/config then lib.importTOML ./.cargo/config else
    if builtins.pathExists ./.cargo/config.toml then lib.importTOML ./.cargo/config.toml else { };
    profilesByName = { };
    rootFeatures' = expandFeatures rootFeatures;
    overridableMkRustCrate = f:
      let
        drvs = genDrvsByProfile profilesByName ({ profile, profileName }: mkRustCrate ({
          inherit release profile hostPlatformCpu hostPlatformFeatures target profileOpts codegenOpts cargoUnstableFlags rustcLinkFlags rustcBuildFlags;
          cargoConfig = cargoConfig';
        } // (f profileName)));
      in
      { compileMode ? null, profileName ? decideProfile compileMode release }:
      let drv = drvs.${profileName}; in if compileMode == null then drv else drv.override { inherit compileMode; };
  in
  {
    cargo2nixVersion = "0.12.0";
    workspace = {
      rust-test = rustPackages.unknown.rust-test."0.1.0";
    };
    "unknown".rust-test."0.1.0" = overridableMkRustCrate (profileName: rec {
      name = "rust-test";
      version = "0.1.0";
      registry = "unknown";
      src = fetchCrateLocal workspaceSrc;
    });

  }
