authors:
  domenkozar:
    name: Domen Kožar
    description: Maintainer
    avatar: https://github.com/domenkozar.png
  sandydoo:
    name: Sander
    description: Maintainer
    avatar: https://github.com/sandydoo.png
