#/usr/bin/env bash

# WARN: to only be run from the root of the repo!

set -ex

output_file=docs/src/reference/options.md
options=$(nix build --accept-flake-config --no-pure-eval --extra-experimental-features 'flakes nix-command' --show-trace --print-out-paths --no-link '.#devenv-docs-options')
echo "[comment]: # (DO NOT MODIFY. This file was generated by devenv-generate-doc-options.)" >$output_file
echo "# devenv.nix" >>$output_file
echo >>$output_file
cat $options >>$output_file
# https://github.com/NixOS/nixpkgs/issues/224661
sed -i 's/\\\././g' $output_file
