{ pkgs, lib, config, ... }:

let
  cfg = config.devcontainer;
  settingsFormatJSON = pkgs.formats.json { };
  file = pkgs.runCommand "devcontainer.json" {
    nativeBuildInputs = [ pkgs.gawk ];
    jsonFile = settingsFormatJSON.generate "devcontainer.json" cfg.settings;
  } ''
    gawk 'NR==1{print "// Generated by devenv. DO NOT EDIT THIS LINE"}1' "$jsonFile" > $out
  '';
in
{
  options.devcontainer = {
    enable = lib.mkEnableOption "generation .devcontainer.json for devenv integration";

    settings = lib.mkOption {
      type = lib.types.submodule {
        freeformType = settingsFormatJSON.type;

        options.image = lib.mkOption {
          type = lib.types.str;
          default = "ghcr.io/cachix/devenv/devcontainer:latest";
          description = ''
            The name of an image in a container registry.
          '';
        };

        options.overrideCommand = lib.mkOption {
          type = lib.types.anything;
          default = false;
          description = ''
            Override the default command.
          '';
        };

        options.updateContentCommand = lib.mkOption {
          type = lib.types.anything;
          default = "devenv test";
          description = ''
            A command to run after the container is created.
          '';
        };

        options.customizations.vscode.extensions = lib.mkOption {
          type = lib.types.listOf lib.types.str;
          default = [ "mkhl.direnv" ];
          description = ''
            A list of pre-installed VS Code extensions.
          '';
        };
      };

      default = { };

      description = ''
        Devcontainer settings.
      '';
    };
  };

  config = {
    tasks."devenv:devcontainer:cleanup" =  lib.mkIf (!config.devcontainer.enable) {
      description = "Cleanup old, unused devcontainer configuration created by devenv";
      exec = ''
      if head -n 1 ${config.env.DEVENV_ROOT}/.devcontainer/devcontainer.json | grep -q "Generated by devenv"; then
        rm -rf ${config.env.DEVENV_ROOT}/.devcontainer
      fi
    '';
      before = [ "devenv:devcontainer" "devenv:enterShell" ];
    };

    tasks."devenv:devcontainer" = {
      description = "Create devcontainer";
      exec = ''
      generate_devcontainer() {
        mkdir -p ${config.env.DEVENV_ROOT}/.devcontainer
        cat ${file} > ${config.env.DEVENV_ROOT}/.devcontainer/devcontainer.json
      }
      if [ -e ${config.env.DEVENV_ROOT}/.devcontainer ]; then
        if head -n 1 ${config.env.DEVENV_ROOT}/.devcontainer/devcontainer.json | grep -qv "Generated by devenv"; then
          mv .devcontainer/ .devcontainer-old/
          echo "Your old devcontainer configuration is available at $PWD/.devcontainer-old directory" 
          generate_devcontainer
        else
          if [ "$(cat ${config.env.DEVENV_ROOT}/.devcontainer/devcontainer.json)" != "$(cat ${file})" ]; then
            generate_devcontainer
          fi
        fi
      else 
        generate_devcontainer
      fi
    '';
      before = [ "devenv:devcontainer" "devenv:enterShell" ];
      after = ["devenv:files"]
    };
  };
}
