[package]
name = "tokio-shutdown"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["sync", "macros", "rt", "signal", "time"] }
tokio-util = { version = "0.7" }
futures = "0.3"
