name: "Auto format"

on:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v17
        with:
          name: devenv

      - name: Install devenv
        # TODO(sander): go back to latest once a release includes the non-TUI stdout fix.
        run: nix profile add github:cachix/devenv/29fcc8a9a778c2e3f822ef961cc9667122e79dd5 -L --accept-flake-config

      - name: Run formatters
        run: devenv shell -- prek run -a || true

      - uses: EndBug/add-and-commit@v10
        with:
          default_author: github_actions
          add: "."
          message: "Auto format code"
