name: "Options docs"
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
    - uses: cachix/cachix-action@v12
      with:
        name: devenv
    - run: nix profile install .
    - name: Generate doc options
      run: devenv shell generate-doc-options
    - uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        add:  docs/reference/options.md
        message: 'Auto generate options'