name: "Build & Test"
on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  buildtest:
    uses: ./.github/workflows/buildtest.yml
    with:
      runs-on: [[ubuntu-latest], [macos-latest], [self-hosted, macOS]]
    secrets: inherit